### ISSUE TITLE
Friend List Bug

### ISSUE THREAD

**Issue by ItzDan** [MCMagicParks/IssueTracker#12]
It says someone is online:
![c0273e369ce84d6fa189f2f68c5a0ef5](https://cloud.githubusercontent.com/assets/14927560/15989588/c465ebbe-3072-11e6-8ab1-4ad5c1300bff.png)
When actually they aren't. Although when you do /msg B(Tab) it comes up with their name but then if you send a message to them it says:
![02c4473c633e49abb41194dc7944d720](https://cloud.githubusercontent.com/assets/14927560/15989595/eb2fb158-3072-11e6-889b-fb018c11f353.png)

**Comment by HiItsBrant** [comment]
We've completely re-written the Friends system. I don't think this should be happening anymore.

**Comment by Legobuilder0813** [comment]
Yes, this bug should be patched now. If there are still problems, please create another issue :smiley:
